name: Build PHAR

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Dump env
      run: composer dump-env prod

    - name: Cache warmup
      run: php new-bin/console cache:warmup

    - name: Download Box
      run: wget https://github.com/box-project/box/releases/download/4.2.0/box.phar

    - name: Autoload dump via /usr/bin/composer
      run: /usr/bin/composer dump-autoload --classmap-authoritative --no-dev

    - name: Run Box
      run: php box.phar compile -vvv

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: kopio.phar
        path: build/kopio.phar
