name: Build PHAR

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Download composer
      run: wget https://github.com/composer/composer/releases/download/2.6.5/composer.phar

    - name: Install dependencies
      run: php composer.phar install --prefer-dist --no-progress

    - name: Dump env
      run: php composer.phar dump-env prod

    - name: Cache warmup
      run: php new-bin/console cache:warmup

    - name: Download Box
      run: wget https://github.com/box-project/box/releases/download/4.3.8/box.phar

    - name: Run Box
      run: php box.phar compile --composer-bin=composer.phar
